-- Connects to the database
\c como_say_what;

-- Populates table(s) with data
INSERT INTO words (english, french, italian, german, spanish, russian, korean, hebrew, hungarian, cantonese, portuguese, dutch) VALUES
  ('planet', 'planète', 'pianeta', 'Planet', 'planeta', 'планета', '행성', 'פלנטה', 'bolygó', '行星', 'planeta', 'planeet'),
  ('athlete', 'athlète', 'atleta', 'Athlet', 'atleta', 'атлет', '선수', 'אתלט', 'sportoló', '運動員', 'atleta', 'atleet'),
  ('weather', 'temps', 'clima', 'Wetter', 'tiempo', 'погода', '날씨', 'מזג אוויר', 'időjárás', '天氣', 'tempo', 'weer'),
  ('trail', 'trace', 'scia', 'Spur', 'camino', 'след', '산책로', 'שובל', 'nyom', '小路', 'trilho', 'spoor'),
  ('storm', 'orage', 'tempesta', 'Sturm', 'tormenta', 'шторм', '태풍', 'סערה', 'vihar', '暴風雨', 'tempestade', 'storm'),
  ('fruit', 'fruit', 'frutto', 'Frucht', 'fruta', 'фрукт', '과일', 'פירות', 'gyümölcs', '水果', 'fruta', 'fruit'),
  ('shadow', 'ombre', 'ombra', 'Schatten', 'sombra', 'тень', '그림자', 'צל', 'árnyék', '影子', 'sombra', 'schaduw'),
  ('dance (noun)', 'danse', 'ballo', 'Tanz', 'baile', 'танец', '춤', 'ריקוד (שם עצם)', 'tánc', '舞蹈', 'dança', 'dans'),
  ('package (noun)', 'emballage', 'pacco', 'Paket', 'paquete', 'упаковка', '소포', 'אריזה (שם עצם)', 'csomag', '包裹', 'pacote', 'pakket'),
  ('e-mail', 'email', 'email', 'E-Mail', 'correo electrónico', 'электронная почта', '이메일', 'דואר אלקטרוני', 'e-mail', '電郵', 'e-mail (or correio eletrónico)', 'e-mail'),
  ('(automobile) traffic', 'trafic', 'traffico', 'Straßenverkehr', 'tráfico', 'пробка', '차량', 'תנועה (כלי רכב)', 'autó', '交通', 'tráfego automóvel', '(Auto) verkeer'),
  ('muscle', 'muscle', 'muscolo', 'Muskel', 'músculo', 'мускул', '근육', 'שריר', 'izom', '肌肉', 'músculo', 'spier'),
  ('cash (not credit)', 'monnaie', 'contante', 'Bargeld', 'efectivo', 'наличные деньги', '현금', 'מזומן (לא אשראי)', 'készpénz', '現金', 'dinheiro', 'contanten'),
  ('museum', 'musée', 'museo', 'Museum', 'museo', 'музей', '박물관', 'מוזיאון', 'múzeum', '博物館', 'museu', 'museum'),
  ('advertisement', 'publicité', 'pubblicità', 'Werbung', 'anuncio', 'реклама', '광고', 'פרסומת', 'reklám', '廣告', 'publicidade', 'advertentie'),
  ('sheet (of paper)', 'feuille', 'foglio (di carta)', 'Blatt Papier', 'hoja', 'лист (бумаги)', '장', 'גיליון (נייר)', 'lap', '紙張', 'folha (de papel)', 'vel (papier)'),
  ('pilot', 'pilote', 'pilota', 'Pilot', 'piloto', 'пилот', '파일럿', 'טיס', 'pilóta', '機師', 'piloto', 'piloot'),
  ('surgery', 'chirurgie', 'chirurgia', 'Operation', 'cirugía', 'операция', '수술', 'ניתוח', 'műtét', '手術', 'cirurgia', 'chirurgie'),
  ('basketball (the ball itself)', 'bal de basket', 'pallone da basket', 'Basketball', 'balón de basketball', 'мяч', '농구공', 'כדורסל (הכדור עצמו)', 'kosárlabda', '籃球', 'bola de basquete', 'basketbal'),
  ('golf', 'golf', 'golf', 'Golfspiel', 'golf', 'гольф', '골프', 'גולף', 'golf', '高爾夫球', 'golfe', 'golf'),
  ('(metal) chain', 'chaine', 'catena', 'Metallkette', 'cadena', 'цепь', '쇠사슬', 'שרשרת (מתכת)', 'lánc', '鐵鏈', 'corrente (de metal)', 'ketting'),
  ('address (street)', 'adresse', 'indirizzo', 'Adresse (Straße)', 'dirección', 'адресс (улица)', '주소', 'כתובת (רחוב)', 'cím', '地址', 'morada (rua)', 'adres (straat)'),
  ('bowl (For cereal)', 'bol', 'scodella', 'Schüssel', 'tazón', 'миска(для каши)', '그릇', 'קערה (לדגני בוקר)', 'tál', '碗', 'tigela (para cereais)', 'kom (voor granen)'),
  ('(symphony) hall', 'grande salle', 'salone', 'Saal', 'salón', '(симфонический) зал', '전당', 'אולם (סימפוניה)', 'terem', '大禮堂', 'salão', '(concert) zaal'),
  ('(dressing room) mirror', 'miroir', 'specchio', 'Spiegel', 'espejo', 'зеркало', '거울', 'מראה (חדר הלבשה)', 'tükör', '化妝室', 'espelho (do vestiário)', '(kleedkamer) spiegel'),
  ('(water) tank', 'citerne', 'acquario', 'Wasserbecken', 'tanque', 'водоем', '수조', 'מיכל (מים)', 'tartály', '(水)箱', 'tanque (de água)', '(water) tank'),
  ('nurse', 'infirmière', 'infermiera', 'Krankenschwester', 'enfermera', 'медсестра', '간호사', 'אחות', 'nővér', '護士', 'enfermeira', 'verpleegster'),
  ('cloud', 'nuage', 'nuvola', 'Wolke', 'nube', 'облако', '구름', 'ענן', 'felhő', '雲', 'nuvem', 'wolk'),
  ('(salt and) pepper', 'poivre', 'pepe', '(Salz und) Pfeffer', 'pimienta', 'соль и перец', '후추', 'פלפל (ומלח)', 'paprika', '(鹽和) 胡椒', '(sal e) pimenta', '(zout en) peper'),
  ('vegetable', 'légume', 'verdura', 'Gemüse', 'vegetal', 'овощ', '야채', 'ירק', 'zöldség', '蔬菜', 'vegetal', 'groente'),
  ('dish (/plate)', 'plat', 'piatto', 'Teller', 'plato', 'блюдо (тарелка)', '그릇', 'מנה', 'tányér', '碟', 'prato', 'schotel (/ plaat)'),
  ('(neck) tie', 'cravate', 'cravatta', 'Krawatte', 'corbata', 'галстук', '넥타이', 'עניבה', 'nyakkendő', '領帶', 'nó de gravata', '(nek) stropdas'),
  ('bomb', 'bombe', 'bomba', 'Bombe', 'bomba', 'бомба', '폭탄', 'פצצה', 'bomba', '炸彈', 'bomba', 'bom'),
  ('engineer', 'ingénieur', 'ingegnere', 'Ingenieur', 'ingeniero', 'инженер', '엔지니어', 'מהנדס', 'mérnök', '工程師', 'engenheiro', 'ingenieur'),
  ('wheel', 'roue', 'ruota', 'Rad', 'rueda', 'колесо', '바퀴', 'גלגל', 'kerék', '車輪', 'roda', 'wiel');
